### ISSUE TITLE
DECORDError

### ISSUE THREAD

**Issue by Nehc** [thavlik/doom-gameplay-dataset#1]
I am trying to use the given decord snippet and I get the error: 

---------------------------------------------------------------------------
DECORDError                               Traceback (most recent call last)
<ipython-input-102-9648f2902783> in <module>
     16 num_frames = 1 # Likely (but not always) synonymous with batch_size
     17 batch_shape = (num_frames, width, height, 3)
---> 18 vl = VideoLoader(video_files,
     19                  ctx=[gpu(0)],
     20                  shape=batch_shape,

D:\Workspace\Anaconda\envs\PyTorch\lib\site-packages\decord\video_loader.py in __init__(self, uris, ctx, shape, interval, skip, shuffle, prefetch)
     52         assert isinstance(shape, (list, tuple))
     53         assert len(shape) == 4, "expected shape: [bs, height, width, 3], given {}".format(shape)
---> 54         self._handle = _CAPI_VideoLoaderGetVideoLoader(
     55             uri, device_types, device_ids, shape[0], shape[1], shape[2], shape[3], interval, skip, shuffle, prefetch)
     56         assert self._handle is not None

D:\Workspace\Anaconda\envs\PyTorch\lib\site-packages\decord\_ffi\_ctypes\function.py in __call__(self, *args)
    171         ret_val = DECORDValue()
    172         ret_tcode = ctypes.c_int()
--> 173         check_call(_LIB.DECORDFuncCall(
    174             self.handle, values, tcodes, ctypes.c_int(num_args),
    175             ctypes.byref(ret_val), ctypes.byref(ret_tcode)))

D:\Workspace\Anaconda\envs\PyTorch\lib\site-packages\decord\_ffi\base.py in check_call(ret)
     76                 err_str = err_str.split('Stack trace')[0].strip()
     77             raise DECORDLimitReachedError(err_str)
---> 78         raise DECORDError(err_str)
     79 
     80 

DECORDError: [23:35:11] D:\a\decord\decord\src\video\video_loader.cc:52: Check failed: key_indices.size() > 0 (0 vs. 0) Error getting key frame info from _9zaLSmRgGc000.mp4

what am I doing wrong?

**Comment by thavlik** [comment]
Hey! I appreciate you bringing this to my attention. I was able to replicate the bug, and rolling the decord version back far enough revealed the example code was only passing the filenames to the VideoLoader, not the full paths. Whoops! The example code is fixed now and is also available at src/decord_test.py. Please let me know if it works.

Thank you!

EDIT: to clarify, the corrected example code should work with any version of decord, including the latest (0.6.0)

**Comment by Nehc** [comment]
Super! Now works as expected. Thanks! )
